# https://pnpm.io/pnpm-workspace_yaml
---
packages:
    - "apps/*" # Applications
    - "libs/*" # Libraries

# https://pnpm.io/catalogs
catalog:
    "@storybook/addon-svelte-csf": "5.0.0-next.3"
    "@storybook/svelte": "8.2.9"
    "@sveltejs/vite-plugin-svelte": "4.0.0-next.6"
    "@total-typescript/tsconfig": "1.0.4"
    "@types/node": "22.5.2"
    "csstype": "3.1.3"
    "rxjs": "7.8.1"
    "storybook": "8.2.9"
    "svelte": "5.0.0-next.221"
    "svelte-check": "4.0.1"
    "typescript": "5.5.4"
    "typescript-svelte-plugin": "0.3.40"
    "unocss": "0.62.3"
