name: Chromatic

on: workflow_call

defaults:
    run:
        shell: bash

env:
    CI: true

permissions:
    contents: write
    pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    chromatic:
        name: Chromatic
        runs-on: macos-latest
        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v4

            - name: Enable corepack (for pnpm)
              # https://nodejs.org/api/corepack.html
              run: corepack enable

            # https://github.com/actions/setup-node
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  node-version-file: ".nvmrc"

            - name: Install Node.js dependencies with pnpm
              # https://pnpm.io/cli/install
              run: >
                  pnpm install
                  --frozen-lockfile

            # https://github.com/chromaui/action
            - name: Upload to Chromatic
              uses: chromaui/action@v11
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  onlyChanged: true
                  exitOnceUploaded: true
